services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  # REST API
    volumes:
      - qdrant_data:/qdrant/storage
      - ./config:/qdrant/config
    environment:
      # - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}"
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__HTTP_PORT=6333
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ai-network
  ai-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: ai-app
    ports:
      - "${API_PORT}:8000"
    command: >
      sh -c "uvicorn --factory src.main:create_app --reload --host 0.0.0.0"
    env_file:
      - "../.env"
    volumes:
      - "..:/app/"
    depends_on:
      - qdrant
    networks:
      - ai-network
  ollama:
    image: docker.io/ollama/ollama:latest
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    # command: 
    pull_policy: always
    tty: true
    restart: always
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local